name: Test / MPSync Plugin

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - ready_for_review
    branches:
      - master

jobs:
  build:
    name: MPSync Plugin / Build
    runs-on: windows-2022
    steps:
      - name: Setup Visual Studio 2022
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 16.11

      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Nuget
        run: |
          nuget restore
        working-directory: ${{ github.workspace }}\MPSync
        shell: cmd

      - name: Build (x86)
        run: |
          build.cmd x86 < nul
        working-directory: ${{ github.workspace }}\build
        shell: cmd

      - name: Build (x64)
        run: |
          build.cmd x64 < nul
        working-directory: ${{ github.workspace }}\build
        shell: cmd

      - name: Upload Artifact / Plugin
        uses: actions/upload-artifact@v5
        if: ${{ success() }}
        with:
          name: MPSync
          path: |
            ${{ github.workspace }}\MPSync\MPSync\bin\Release\MPSync.dll
          retention-days: ${{ inputs.retention-build || 90 }}
          if-no-files-found: error

  ci-status:
    name: Build Status
    runs-on: ubuntu-latest
    needs:
      - build
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
